// Bundles all js/*.js modules into a single dist/bundle.js so the game
// can be played by double-clicking index.html (no ES Modules / no server).
//
// Run: `node build.js`

const fs = require('fs');
const path = require('path');

const order = [
  'config', 'grid', 'assets', 'audio', 'particles', 'sun',
  'projectiles', 'zombies', 'mower', 'plants',
  'levels', 'ui', 'renderer', 'game', 'input', 'main',
];

const root = __dirname;
const distDir = path.join(root, 'dist');
if (!fs.existsSync(distDir)) fs.mkdirSync(distDir);

let bundle = '';

for (const name of order) {
  const file = path.join(root, 'js', `${name}.js`);
  let src = fs.readFileSync(file, 'utf8');

  // Strip multi-line and single-line `import ... from '...';`
  src = src.replace(/^\s*import\s+[\s\S]*?from\s+['"][^'"]+['"];?\s*$/gm, '');

  // Strip `export ` prefix on declarations and re-exports
  src = src.replace(/^\s*export\s+(class|function|const|let|var|async\s+function)\b/gm, '$1');

  // Strip `export { ... };` re-export blocks if any (not used here, but safe)
  src = src.replace(/^\s*export\s*\{[\s\S]*?\};?\s*$/gm, '');

  bundle += `// ============ ${name}.js ============\n${src.trim()}\n\n`;
}

// Wrap in an IIFE so we don't pollute window with hundreds of symbols.
const wrapped = `// AUTO-GENERATED by build.js — do not edit directly.
(function(){
'use strict';

${bundle}
})();
`;

const outFile = path.join(distDir, 'bundle.js');
fs.writeFileSync(outFile, wrapped, 'utf8');
console.log(`Wrote ${outFile} (${(wrapped.length / 1024).toFixed(1)} KB)`);
