export const level1 = {
  id: 'level1',
  name: '关卡 1 — 白天后院',
  startingSun: 50,
  waves: [
    {
      triggerTime: 12,
      announceText: null,
      zombies: [
        { type: 'basic', delay: 0 },
        { type: 'basic', delay: 7 },
        { type: 'basic', delay: 13 },
        { type: 'basic', delay: 19 },
        { type: 'basic', delay: 25 },
      ],
    },
    {
      triggerTime: 50,
      announceText: '一大波僵尸即将来袭！',
      zombies: [
        { type: 'basic', delay: 0 },
        { type: 'basic', delay: 4 },
        { type: 'cone',  delay: 9 },
        { type: 'basic', delay: 14 },
        { type: 'basic', delay: 18 },
        { type: 'cone',  delay: 23 },
        { type: 'basic', delay: 28 },
        { type: 'cone',  delay: 33 },
        { type: 'basic', delay: 37 },
        { type: 'basic', delay: 42 },
      ],
    },
    {
      triggerTime: 105,
      announceText: '最终大波僵尸！',
      zombies: [
        { type: 'basic',  delay: 0 },
        { type: 'cone',   delay: 3 },
        { type: 'basic',  delay: 7 },
        { type: 'cone',   delay: 11 },
        { type: 'bucket', delay: 15 },
        { type: 'basic',  delay: 19 },
        { type: 'cone',   delay: 23 },
        { type: 'basic',  delay: 27 },
        { type: 'cone',   delay: 30 },
        { type: 'bucket', delay: 34 },
        { type: 'cone',   delay: 38 },
        { type: 'basic',  delay: 42 },
        { type: 'bucket', delay: 46 },
        { type: 'basic',  delay: 50 },
        { type: 'bucket', delay: 54 },
      ],
    },
  ],
};
